<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <AssemblyName>WebpageWaiterTests</AssemblyName>
        <TargetFramework>net48</TargetFramework>
        <IsTestProject>true</IsTestProject>
        <PlatformTarget>AnyCPU</PlatformTarget>
        <ImplicitUsings>disable</ImplicitUsings>
        <Nullable>disable</Nullable>
        <AssemblyOriginatorKeyFile>Key.snk</AssemblyOriginatorKeyFile>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="NUnit" Version="3.14.0" />
        <PackageReference Include="NUnit3TestAdapter" Version="4.6.0">
            <PrivateAssets>all</PrivateAssets>
        </PackageReference>
        <PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.11.1" />
    </ItemGroup>

    <ItemGroup>
    <ProjectReference Include="..\WebpageWaiter\WebpageWaiter.csproj" />
    </ItemGroup>

    <!-- Debug: gegen das KeePass-Projekt bauen -->
    <ItemGroup Condition=" '$(Configuration)' == 'Debug' ">
        <ProjectReference Include="..\KeePass\KeePass\KeePass_N48.csproj">
            <Project>{10938016-dee2-4a25-9a5a-8fd3444379ca}</Project>
            <Name>KeePass_N48</Name>
        </ProjectReference>
    </ItemGroup>

    <!-- Release: gegen die signierte KeePass.exe bauen.
         Costura-Referenz nur in Release. -->
    <ItemGroup Condition=" '$(Configuration)' == 'Release' ">
        <Reference Include="Costura, Version=6.2.0.0, Culture=neutral, PublicKeyToken=9919ef960d84173d, processorArchitecture=MSIL">
            <HintPath>..\packages\Costura.Fody.6.2.0\lib\netstandard2.0\Costura.dll</HintPath>
        </Reference>
        <Reference Include="KeePass">
            <HintPath>..\Resources\KeePass.exe</HintPath>
        </Reference>
    </ItemGroup>



<!--    <ItemGroup Condition="'$(Configuration)' == 'Debug'">-->
<!--        <ContentWithTargetPath Include="Resources\**">-->
<!--            <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>-->
<!--            <TargetPath>%(RecursiveDir)\%(Filename)%(Extension)</TargetPath>-->
<!--        </ContentWithTargetPath>-->
<!--    </ItemGroup>-->


</Project>